### PR TITLE
Standardise 'not' operator usage

### PR DESCRIPTION
**Pull request by john-n-smith**

### CODE REVIEW

**Comment by wpillar** [comment]
Regardless of the result, I'd like to request that a CodeSniffer check is written and implemented. If we want consistency, let's have consistency. Should be one that can be autofixed.

Grab me if you need help writing the check.

**Comment by john-n-smith** [comment]
Agree. Will do.

**Comment by sjparkinson** [comment]
I'd imagine a sniff for that already exists?

**Comment by john-n-smith** [comment]
Just had a look, apparently not. 

(Squizlab's coding style is horrible)

**Comment by wpillar** [comment]
@john-n-smith should we merge this? Or wait for the code sniff?

**Pull request merged**
