### PR TITLE
Error for underscore prefixes

### PR DESCRIPTION
**Pull request by wpillar**

### CODE REVIEW

**Comment by wpillar** [comment]
@mathieupinet @brendankay @john-n-smith @jakewright @sjparkinson @notlee seem ok?

It's currently a warning, I think it should be an error.

**Comment by brendankay** [comment]
Fine by me

**Comment by mathieupinet** [comment]
sure

**Comment by sjparkinson** [comment]
:+1:

**Comment by wpillar** [comment]
Going to merge this unless there are any objections... @john-n-smith @jakewright @notlee

**Comment by sjparkinson** [comment]
:ok_hand:

**Pull request merged**
